---
# Partition Module Configuration for Amelia
userSwapChoices:
  - none
  - small
  - suspend
  - file

defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"

efi:
    mountPoint: "/boot/efi"
    recommendedSize: 300
    minimumSize: 300
    label: "EFI"
