---
# Welcome Module Configuration for Amelia
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
    requiredStorage: 15
    requiredRam: 2.0
    internetCheckUrl: http://ping.debian.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
